### ISSUE TITLE
Implement offline installation support without a proxy server

### ISSUE THREAD

**Issue by Anton-PG** [vitabaks/postgresql_cluster#10]
RU: Хотелось бы, что бы вы реализовали поддержку offline установки без прокси сервера.

EN: I would like you to implement support for offline installations without a proxy server.

**Comment by markwort** [comment]
hey, if you're on Fedora 30, CentOS 7 or RHEL 7, you could use these packages:
https://github.com/cybertec-postgresql/patroni-packaging/releases

Then, download the package locally, copy to server and install there...
```
    - name: Download patroni
      local_action: get_url
      args:
        url: "https://github.com/cybertec-postgresql/patroni-packaging/releases/download/1.6.0-1/patroni-1.6.0-1.rhel7.x86_64.rpm"
        dest: "/tmp/patroni-1.6.0-1.rhel7.x86_64.rpm"

    - name: copy patroni package
      copy:
        src: "/tmp/patroni-1.6.0-1.rhel7.x86_64.rpm"
        dest: "/tmp/patroni-1.6.0-1.rhel7.x86_64.rpm"

    - name: install epel to provide python36-psycopg2 dependency for patroni
      shell: 'yum install -y epel-release'

    - name: install patroni package
      yum:
        name: /tmp/patroni-1.6.0-1.rhel7.x86_64.rpm
        state: present
```

I have not yet found a nice way of installing epel-release directly via the yum module. (Ansible complains everytime I run it...)
It may be nicer to run:
```
    - name: install epel to provide python36-psycopg2 dependency for patroni
      yum:
        name:  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
```
The epel rpm could then also be downloaded locally and copied beforedhand...

Just something to think about!

**Comment by vitabaks** [comment]
Hello friends!

I have already received several requests for the implementation of fully autonomous installation support (without a proxy server). Perhaps this is somehow related to the company's security rules...
I will try to help you and begin to implement this idea in the near future.

> hey, if you're on Fedora 30, CentOS 7 or RHEL 7, you could use these packages:

@markwort Thank you very much! 
I have already found the “deb” patroni packages for the Debian distribution, but I could not find the “rpm” packages for CentOS before.
deb packages: https://apt.postgresql.org/pub/repos/apt/pool/main/p/patroni/
Therefore, your rpm packages may be useful to someone.

But, I use official packages from the pip repository for installation. These packages are suitable for all distributions. https://pypi.org/project/patroni/
I believe that you need to use pip packages. And i still do not understand what is the advantage in using packages of my own assembly.

But, maybe it’s worth implementing the option to choose the installation method ("pip" or "rpm/deb" packages).


>  Then, download the package locally, copy to server and install there...

I think @Anton-PG has in mind the installation method when there is no direct access to the Internet or the possibility of using a proxy server even on a managed machine.

> I have not yet found a nice way of installing epel-release directly via the yum module. (Ansible complains everytime I run it...)

We already use a similar method to install the epel repository.
See the code "Install Epel Repository" in tasks/add-repository.yml file.

But, there is no point in installing the Epel repository if the target servers do not have Internet access or a proxy server ...
You will need to preload all the necessary packages into your own repository.
Then, replace the paths for additional packages in the variable file.

I am thinking of putting all the urls in the vars/Debian.yml and vars/RedHat.yml files.

**Comment by vitabaks** [comment]
Done.
See **dev** branch.

I would be grateful if you could help me with testing these changes. Please check the functionality listed below in your test environment.

What's new:
1. Now, you can use your own repository for extra packages. You need to preload all the packages and change URLs.
For your convenience, all URLs have been moved to the vars/Debian.yml and vars/RedHat.yml variable files.

See this variables: 
etcd_package_repo, vip_manager_package_repo, haproxy_package_repo, haproxy_compile_requirements, lua_package_repo, confd_package_repo.

Patroni packages will be installed from the pip repository (by default).
You can use your repository to install pip packages instead of the external pip repository.

See this variables: 
pip_package_repo, patroni_pip_requirements_repo, patroni_pip_package_repo

(TODO) You also have the option of choosing an patroni installation method using the rpm or deb package.

Variables: "patroni_installation_method" and "patroni_rpm_package_repo" (for Redhat) or "patroni_deb_package_repo" (for Debian).


2. If you don't have your own repository .... or do you want to create something like "offline installer package":
You can download the necessary packages into postgresql_cluster/files/ directory. Packages from this directory will be used for installation.

"installation_method" and "<variable_name>_file" variables.

but,
this is probably a more difficult installation method, 
since you need to download all packages (system_packages, postgresql_packages, haproxy_compile_requirements, keepalived, pgbouncer ...) 
also you have determine all dependencies , and point them in the correct order...
You can download the necessary packages into postgresql_cluster/files/ directory. And specify the "packages_from_file" variable.
This packages will be installed before all other packages.

P.S.
The installation method using a proxy server is considered the simplest and fastest for the initial deployment of the cluster.
(all dependencies will be automatically downloaded and installed).

**Comment by vitabaks** [comment]
Tested on Debian 9/10, Ubuntu 18.04, CentOS 7.6
With Ansbile 2.8.5

The following installation methods were tested:
1. installation_method: "repo" and patroni_installation_method: "pip"
1.1. from external repositories;
1.2. from local repository (variables: pip_package_repo, patroni_pip_requirements_repo, patroni_pip_package_repo).

2. installation_method: "repo" and patroni_installation_method: "deb" and "rpm"
2.1. from external postgresql apt repository (for debian/ubuntu) and cybertec-postgresql github repo (for CentOS);
2.2. from local repository.

3. installation_method: "file" and patroni_installation_method: "pip" (with pre-installed dependencies*)
4. installation_method: "file" and patroni_installation_method: "deb" and "rpm" (with pre-installed dependencies*)


To test the "file" method, there were pre-installed dependent packages from the local YUM/APT repository.
You can define each dependent package in the packages_from_file variable for installation without APT/YUM repository.

I would be grateful if you could help to make a complete list of dependencies for later installation via the packages_from_file variable.
I am not yet ready to allocate time for this.

**Comment by Anton-PG** [comment]
Good afternoon!
I am ready to help with listing for the packages_from_file variable!

**Comment by vitabaks** [comment]
Please give feedback.
Or this issue will be closed after 7 days due to inactivity.

**Comment by Tesnim-Trk** [comment]
Hi Community, I an trying to install patroni for postgres HA in an offline environment. its rhel 8 environment
I copied the pip.zip and installed pip3 offline. this is working but if I need to install patroni with pip, it is trying to connect to internet to get the packages which is not possible in my case. same for other dependencies like psycopg2-binary. 
I tried copying the patroni package from https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-8.6-x86_64/ and installing it locally but I can't specify dependencies, I need to install it with only etcd and consul. also when trying to start it is not started and throwing errors 
 Failed to import patroni.dcs.consul
 Failed to import patroni.dcs.etcd
 Failed to import patroni.dcs.etcd3
 Failed to import patroni.dcs.exhibitor
 Failed to import patroni.dcs.raft
 Failed to import patroni.dcs.zookeeper

**Comment by vitabaks** [comment]
@Tesnim-Trk Hi! Offline installation is a more complex installation method than using a proxy server, so I usually recommend using a proxy server for closed environments. 

Example:
```yaml
installation_method: "file"
patroni_installation_method: "rpm"
patroni_rpm_package_file: "patroni-3.2.2-1PGDG.rhel8.noarch.rpm"
etcd_package_file: "etcd-v3.5.11-linux-amd64.tar.gz" 
packages_from_file:
  - any
  - other
  - rpm
...
```
Note: The pip method for offline installation is even more difficult, try rpm instead.

Or, You can also use your own repository for extra packages. You need to preload all the packages and change this URLs.

```yaml
installation_method: "repo"
```

See `vars/RedHat.yml` for details.

P.S.
In fact, I'm thinking about removing offline installation support in subsequent releases, because I don't think this feature is so necessary and it complicates code support.
