### ISSUE TITLE
Could not enable "PowerTools repository" on RHEL8

### ISSUE THREAD

**Issue by SomeAverageDev** [vitabaks/postgresql_cluster#298]
Hello,
First, thank you for this great playbook ! 

I have an issue while running the latest playbook version, on repositories tasks.

```
    # PowerTools repository (to install dependencies for postgresql<version>-devel package)
    - name: Enable PowerTools repository
      command: dnf config-manager --set-enabled "[Pp]ower[Tt]ools"
      when:
        - ansible_distribution_major_version is version('8', '==')
        - ansible_distribution != "OracleLinux"
```

The power tools repo is not declared on the RHEL8 server (we are using internal Satellite, it could come from that also, I will try to check with my colleagues)

Please find the task log below:

```
TASK [add-repository : Enable PowerTools repository] ***********************************************************************************************************************************************************************************************************************************************************
fatal: [x.x.x.]: FAILED! => {"changed": true, "cmd": ["dnf", "config-manager", "--set-enabled", "[Pp]ower[Tt]ools"], "delta": "0:00:00.787755", "end": "2023-04-05 17:46:40.373527", "msg": "non-zero return code", "rc": 1, "start": "2023-04-05 17:46:39.585772", "stderr": "Error: No matching repo to modify: [Pp]ower[Tt]ools.", "stderr_lines": ["Error: No matching repo to modify: [Pp]ower[Tt]ools."], "stdout": "Updating Subscription Management repositories.", "stdout_lines": ["Updating Subscription Management repositories."]}
```

This repo does not look necessary though in my installation context... don't really know if I need it.
