### ISSUE TITLE
postgresql cluster (patroni) with timescaledb.

### ISSUE THREAD

**Issue by vitabaks** [vitabaks/postgresql_cluster#31]
[![Timescale](https://dbdb.io/media/logos/Timescale.png)](https://www.timescale.com)

**Question:**

Could you please send across, or the changes that i need to make on postgresql cluster to make it work for timescaledb.

**Answer:**

Everything is very simple!
And I myself use timescaledb in production in this cluster scheme.

Please read the documentation to get started: https://docs.timescale.com/latest/getting-started/installation/

**Example for:**
Installation on: `Debian`
Install method: `apt`
PostgreSQL version: `15`

1. **Add timescaledb repository** to download packages (in the [/vars/Debian.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/Debian.yml) variable file):
```
apt_repository_keys:
  - key: "https://www.postgresql.org/media/keys/ACCC4CF8.asc" # postgresql repository apt key
  - key: "https://packagecloud.io/timescale/timescaledb/gpgkey" # timescaledb repository apt key

apt_repository:
  - repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main" # postgresql apt repository
  - repo: "deb https://packagecloud.io/timescale/timescaledb/debian/ {{ ansible_distribution_release }} main" # timescaledb apt repository
```

2. **Add timescaledb packages** for automatic installation in the `postgresql_packages` variable (in the [/vars/Debian.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/Debian.yml) variable file):
```
postgresql_packages:
  - postgresql-{{ postgresql_version }}
  - postgresql-client-{{ postgresql_version }}
  - postgresql-server-dev-{{ postgresql_version }}
  - postgresql-contrib-{{ postgresql_version }}
  - timescaledb-2-postgresql-{{ postgresql_version }}
```

3.  Add/edit the necessary **PostgreSQL parameters for timescaledb** (in the [/vars/main.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/main.yml) variable file):

```
postgresql_version: "15"

postgresql_users: # this is optional
postgresql_databases: # this is optional
postgresql_extensions:
  - {ext: "timescaledb", db: "postgres"} # or my database name

postgresql_parameters:
  - {option: "max_locks_per_transaction", value: "512"}
  - {option: "shared_preload_libraries", value: "timescaledb"}
```

Specify all other variables according to your personal requirements for the database cluster.

### Deployment: [quick start](https://github.com/vitabaks/postgresql_cluster#deployment-quick-start)

**Comment by vitabaks** [comment]
timescaledb repository for **RHEL/CentOS 7/8** (in the [/vars/RedHat.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/RedHat.yml) variable file)

```
yum_repository:
  - name: "timescale_timescaledb"
    description: "timescaledb repo"
    baseurl: "https://packagecloud.io/timescale/timescaledb/el/{{ ansible_distribution_major_version }}/x86_64"
    gpgkey: "https://packagecloud.io/timescale/timescaledb/gpgkey"
    gpgcheck: "no"
```

**Comment by vitabaks** [comment]
timescaledb repository for **Ubuntu** (in the [/vars/Debian.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/Debian.yml) variable file):

```
apt_repository_keys:
  - key: "https://www.postgresql.org/media/keys/ACCC4CF8.asc" # postgresql repository apt key
  - key: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x55ee6bf7698e3d58d72c0dd9ecb3980cc59e610b" # timescaledb PPA repository key

apt_repository:
  - repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main" # postgresql apt repository
  - repo: "deb http://ppa.launchpad.net/timescale/timescaledb-ppa/ubuntu {{ ansible_distribution_release }} main" # timescaledb PPA repository
```
