### ISSUE TITLE
Fix `tput: No value for $TERM and no -T specified` error in GitHub Actions pipeline

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#312]
Hello,

I encountered an issue in the GitHub Actions pipeline, where I'm seeing the following error:

```bash
tput: No value for $TERM and no -T specified
```

This error seems to occur due to the lack of a terminal environment in the GitHub Actions runner, which causes the `tput` command to fail.

In order to resolve this issue, I suggest setting the `TERM` environment variable in the GitHub Actions workflow file. Here's an example of how to update the workflow file:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run pipeline commands
        run: |
          # Your pipeline commands here
```

By setting the `TERM` environment variable, the `tput` command should work as expected, and the error should no longer occur. Please let me know if you need any additional information or if you have any suggestions on how to improve this solution.

Thank you for your time and assistance!
