### ISSUE TITLE
Move Gitpod Dockerfile to .config/gitpod and update .gitpod.yml

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#313]
Hello,

I would like to suggest moving the Gitpod Dockerfile from its current location in the root of the project to the .config/gitpod folder. This would help keep the project more organized and easier to maintain. Here's the proposed change:

From:
```
.gitpod.Dockerfile
```

To:
```
.config/gitpod/Dockerfile
```

Additionally, the .gitpod.yml file needs to be updated to reflect this change. The current content of the file is:

```yaml
---
image:
  file: .config/gitpod/Dockerfile

tasks:
  - init: make bootstrap
```

However, it should be updated to:

```yaml
---
image:
  file: .config/gitpod/Dockerfile

tasks:
  - init: make bootstrap
```

Please let me know if you have any questions or need more information. I'd be happy to provide further assistance or create a pull request if you would like.

Thank you for your attention and consideration.
