### ISSUE TITLE
Implement DRY principle with a shared config.yml file for Molecule scenarios

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#323]
Hello,

I've noticed that the Ansible project uses Molecule for testing, and there are multiple scenarios defined within the project. 
In order to make the project more maintainable and adhere to the DRY (Don't Repeat Yourself) principle, I would like to suggest introducing a shared configuration file for the Molecule scenarios.

The shared configuration file can be named `config.yml` and should store default values for the `molecule.yml` files in each scenario. This file can be placed at the repository level or at the user level. I recommend storing the config file at the repository level for better maintainability and easier collaboration:

- `.config/molecule/config.yml` (recommended)

https://molecule.readthedocs.io/configuration/#prerun:~:text=Keep%20in%20mind%20that%20you%20can%20add%20this%20value%20to%20the%20.config/molecule/config.yml%20file%2C%20in%20your%20%24HOME%20or%20at%20the%20root%20of%20your%20project%2C%20in%20order%20to%20avoid%20adding%20it%20to%20each%20scenario.

With this setup, any key defined in a specific `molecule.yml` file will override the values from the shared `config.yml` file.

```yaml
# .config/molecule/config.yml
driver:
  name: delegated  # <-- now default driver will be delegated
lint: ansible-lint -v
```

```yaml
# molecule.yml
driver:
  name: docker
```

```yaml
# what is effectively loaded
driver:
  name: docker
lint: ansible-lint -v
```

I believe this change will improve the project structure and make it easier for contributors to work on the project. I'd appreciate your thoughts on this suggestion, and if you're interested, I'd be happy to help implement it.

Thank you for your time and consideration!
