### ISSUE TITLE
Add a GitHub Action for Docker (make docker-build)

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#353]
Hello,

As we know, Docker is a key part of our infrastructure, and we need to ensure that changes to the repository do not inadvertently break the Docker build process. To this end, I propose that we add a GitHub Action that will automatically execute `make docker-build` whenever changes are pushed to the repository. This will help us catch potential issues early and ensure that our Docker environment remains stable and reliable.

This action can be set up in a new workflow file under the `.github/workflows` directory, and it would look something like this:

```yaml
name: Docker Build Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Build Test
      run: make reinitialization && make docker-build
```

This setup will run the `make docker-build` command on every push or pull request, ensuring that our Docker build is always functional.

Please let me know your thoughts on this. If there's consensus on the idea, I'd be happy to take the lead on implementing this feature.

Best,
