### ISSUE TITLE
Vip-manager access?

### ISSUE THREAD

**Issue by heyt0ny** [vitabaks/postgresql_cluster#36]
Hi!

Thanks for such a good repo. I'm trying to deploy it to 3 nodes in private network on DO. Everything works fine, but I can't understand how to access db through vip-manager (so I always access db though one ip address).

 What should I put to `vip-manager` in `vars/main.yml`?

**Comment by vitabaks** [comment]
In the default scheme [Type B] - `with_haproxy_load_balancing`: `false`
To provide a single entry point (VIP) for databases access is used "vip-manager".

> What should I put to vip-manager in vars/main.yml?

In variable `cluster_vip` must specify the ip address for your subnet.
This address must be used for client access to databases in the cluster.

**Comment by heyt0ny** [comment]
Thanks, am I correct that it will work if the subnet consists of only Postgres instances? 

I am asking because I'm trying to deploy it in DO private VPC ( which includes other non-postgres droplets) and the ansible gives error on step of `virtual-manager restart ` due to 60 seconds timeout. (And DO is unable to create subnet inside VPC)

**Comment by vitabaks** [comment]
> I am asking because I'm trying to deploy it in DO private VPC

This playbook is designed for deploying in its own data center (on-premise, self-hosted) and has not been tested on VPC and other cloud solutions.

If you have an error during the execution of the "Wait for the cluster ip address (VIP)" {{cluster_vip}} "is running" task, then you have closed access to ssh.
```
- name: Wait for the cluster ip address (VIP) "{{ cluster_vip }}" is running
  wait_for:
    host: "{{ cluster_vip }}"
    port: "{{ ansible_ssh_port }}"
    state: started
    timeout: 60
    delay: 2
```

Maybe I should replace the check with postgresql_port instead of ansible_ssh_port.
Please check the availability of ssh and postgresql ports (between cluster nodes) using telnet.
