### ISSUE TITLE
postgresql cluster (patroni) with PostgresPro

### ISSUE THREAD

**Issue by ib2828** [vitabaks/postgresql_cluster#38]
[![postgrespro](https://postgrespro.ru/img/PostgresPro_Logo_lg.png)](https://postgrespro.ru/products/postgrespro)

Compatibility with Postgres Pro Standard

> :heavy_exclamation_mark: To use any version of Postgres Pro, **you must purchase a license**. You can get the version of the DBMS you are interested in for free for testing, exploring the capabilities of the DBMS, and developing application software.

**Comment by BatomunkuevIgor** [comment]
$ telnet pgnode01 8008
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
Trying 172.24.14.118...
Connected to pgnode01.
Escape character is '^]'.

**Comment by vitabaks** [comment]
This should be tested in detail.

**Comment by vitabaks** [comment]
**Example for:**
Installation on: `СentOS`
PostgreSQL version: `12`

1. **Add PostgresPro repository** for RHEL/CentOS 7/8 (in the [/vars/RedHat.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/RedHat.yml) variable file)

```
yum_repository:
  - name: "postgrespro-std"
    description: "Postgres Pro Standard repo"
    baseurl: "http://repo.postgrespro.ru//pgpro-archive/pgpro-12.2.1/centos/{{ ansible_distribution_major_version }}/os/x86_64/rpms"
    gpgkey: "http://repo.postgrespro.ru/keys/GPG-KEY-POSTGRESPRO"
    gpgcheck: "yes"
```

2. **Add PostgresPro packages** for automatic installation in the `postgresql_packages` variable (in the [/vars/RedHat.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/RedHat.yml) variable file):

```
postgresql_packages:
  - postgrespro-std-{{ postgresql_version }}-server
  - postgrespro-std-{{ postgresql_version }}-client
  - postgrespro-std-{{ postgresql_version }}-contrib
  - postgrespro-std-{{ postgresql_version }}-devel
```


3.  Add/edit the necessary **PostgreSQL parameters** (in the [/vars/main.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/main.yml) variable file):

```
postgresql_version: "12"

postgresql_users:  # this is optional
postgresql_databases:  # this is optional
postgresql_extensions:  # this is optional

postgresql_parameters:
  - {option: "max_connections", value: "100"}
  - {option: "superuser_reserved_connections", value: "5"}
  - {option: "max_locks_per_transaction", value: "512"}
  ...
```

Specify all other variables according to your personal requirements for the database cluster.

### Deployment: [quick start](https://github.com/vitabaks/postgresql_cluster#deployment-quick-start)

**Comment by vitabaks** [comment]
```
postgresql_bin_dir: "/opt/pgpro/std-{{ postgresql_version }}/bin"
```

**Comment by vitabaks** [comment]
for CentOS version **8**
Add python2 package:
```
os_specific_packages:
  RedHat-8:
    - python2  # required for pgbouncer from postgrespro repo
```

**Comment by vitabaks** [comment]
Tested with Postgres Pro Standard 12.2.1 on Centos 7 and 8.

**Comment by vitabaks** [comment]
Tested with Postgres Pro Standard 12.2.1 on Debian 9/10 , Ubuntu 18.04


**PostgresPro repository for Debian / Ubuntu**  (in the /vars/[Debian.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/Debian.yml) variable file)
```
apt_repository_keys:
  - key: "http://repo.postgrespro.ru/keys/GPG-KEY-POSTGRESPRO"
apt_repository:
  - repo: "deb http://repo.postgrespro.ru//pgpro-archive/pgpro-12.2.1/{{ ansible_distribution |lower }}/ {{ ansible_distribution_release }} main"
```
**dev** package is named differently _(different from RHEL)_
```
postgresql_packages:
  - postgrespro-std-{{ postgresql_version }}-server
  - postgrespro-std-{{ postgresql_version }}-client
  - postgrespro-std-{{ postgresql_version }}-contrib
  - postgrespro-std-{{ postgresql_version }}-dev
```
