### ISSUE TITLE
error in syntax /postgresql_cluster/roles/timezone/tasks/main.yml

### ISSUE THREAD

**Issue by emanfeah** [vitabaks/postgresql_cluster#383]
hello , i think the file it's updated and there is some issuse in syntax : 

```
The error appears to be in '/home/ubuntu/postgresql_cluster/roles/timezone/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Set timezone to "{{ timezone }}"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

-------------------------

```
- name: Set timezone to "{{ timezone }}"
  become: true
  become_method: sudo
  community.general.timezone:
    name: "{{ timezone }}"
  when: timezone is defined and timezone | length > 0
  tags: timezone

...
```

any idea what the wrong here ..?
