### ISSUE TITLE
unable to SSH into your server after a reboot

### ISSUE THREAD

**Issue by emanfeah** [vitabaks/postgresql_cluster#411]
hello agian , 

i don't know why when i reboot a replica server I can't ssh it give me .

22 port refused after , maybe because something in playbook

**Comment by vitabaks** [comment]
Hmm, I do not have such a problem.

try a connection with the `ssh -v` option to get detailed output and a trace that can help identify possible problems.

Can you connect to the server in other ways? For example, a console in a cloud platform or your hypervisor. To check the system logs, the status of the sshd service.

By the way, have you included the firewall_enabled_at_boot variable for configuring iptables?

**Comment by emanfeah** [comment]
```
`firewall_enabled_at_boot: true  # or 'true' for configure firewall (iptables)

firewall_allowed_tcp_ports_for:
  master:
    - "8008"
    - "5432"
    - "6432"
  replica:
    - "8008"
    - "5432"
    - "6432"
  pgbackrest: []
  postgres_cluster:
    - "{{ ansible_ssh_port | default(22) }}"
    - "{{ postgresql_port }}"
    - "{{ pgbouncer_listen_port }}"
    - "8008"
    - "19999"  # Netdata
#    - "10050"  # Zabbix agent
#    - ""
  etcd_cluster:
    - "{{ ansible_ssh_port | default(22) }}"
    - "2379"  # ETCD port
    - "2380"  # ETCD port
#    - ""`
```
its that  what you mean ..
