### ISSUE TITLE
Update of GitHub Actions to Prevent Triggering During Draft Pull Requests

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#418]
Hello,

I have noticed that our GitHub Actions are currently being triggered even when pull requests are in draft mode. This may lead to an unnecessary usage of resources and potentially unwanted notifications.

I would like to propose that we update our GitHub Actions to prevent them from being triggered when pull requests are in draft mode. This could be achieved by adding a condition to our GitHub Actions workflows to check the status of the pull request.

Here is an example of how this could be implemented:

```yaml
name: Workflow Name
...
jobs:
  build:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
...
```

In this example, the "build" job only runs if the pull request is not in draft mode.

I would be grateful to hear your thoughts on this proposal.
