### ISSUE TITLE
Error init cluster from pgbackrest backup

### ISSUE THREAD

**Issue by jidckii** [vitabaks/postgresql_cluster#44]
Привет!
Я тут столкнулся с проблемой при инициализации кластера из бэкапа pgbackrest
```
TASK [patroni : Run "/usr/bin/pgbackrest --stanza=sdelka --delta restore" on Master] ******************************************************************************************************************************
changed: [172.30.102.110]
Friday 07 August 2020  12:17:43 +0500 (0:00:02.191)       0:03:13.031 ********* 
Friday 07 August 2020  12:17:43 +0500 (0:00:00.144)       0:03:13.176 ********* 

TASK [patroni : Waiting for restore from backup] ******************************************************************************************************************************************************************
failed: [172.30.102.110] (item=True) => {"ansible_job_id": "317881301454.4512", "ansible_loop_var": "item", "attempts": 1, "changed": false, "cmd": "/var/tmp/ansible-tmp-1596784661.27-18286-75430763482321/AnsiballZ_command.py", "finished": 1, "item": {"ansible_job_id": "317881301454.4512", "changed": true, "failed": false, "finished": 0, "results_file": "/var/lib/postgresql/.ansible_async/317881301454.4512", "started": 1}, "msg": "[Errno 13] Permission denied: '/var/tmp/ansible-tmp-1596784661.27-18286-75430763482321/AnsiballZ_command.py'", "outdata": "", "stderr": "", "stderr_lines": []}

```
Мне кажется этот блог выглядит как магия ...
Может как то упростить этот кусок ?
```
 - block:  # for pgbackrest only (for use --delta restore)
        - name: Run "{{ pgbackrest_patroni_cluster_restore_command }}" on Master
          command: >
            {{ pgbackrest_patroni_cluster_restore_command }}
            {{ '--target-action=promote' if pgbackrest_patroni_cluster_restore_command is search('--type=') else '' }}
          async: 86400  # timeout 24 hours
          poll: 0
          register: pgbackrest_restore_master
          when: is_master == "true"

          # if patroni_create_replica_methods: "pgbackrest"
        - name: Run "{{ pgbackrest_patroni_cluster_restore_command }}" on Replica
          command: >
            {{ pgbackrest_patroni_cluster_restore_command }}
            {{ '--target-action=shutdown' if pgbackrest_patroni_cluster_restore_command is search('--type=') else '' }}
          async: 86400  # timeout 24 hours
          poll: 0
          register: pgbackrest_restore_replica
          when: is_master != "true" and 'pgbackrest' in patroni_create_replica_methods

        - name: Waiting for restore from backup
          async_status:
            jid: "{{ item.ansible_job_id }}"
          loop:
            - "{{ pgbackrest_restore_master }}"
            - "{{ pgbackrest_restore_replica }}"
          loop_control:
            label: "{{ item.changed }}"
          register: pgbackrest_restore_jobs_result
          until: pgbackrest_restore_jobs_result.finished
          retries: 2880  # timeout 24 hours
          delay: 30
          when: item.ansible_job_id is defined
```

**Comment by vitabaks** [comment]
> Мне кажется этот блог выглядит как магия ...
Может как то упростить этот кусок ?

А в чём именно по Вашему мнению заключается магия?
Что Вы предлагаете упростить? 
Логика итак простая. Если мастер '--target-action=promote, если реплика '--target-action=shutdown'

> [Errno 13] Permission denied: '/var/tmp/ansible-tmp-1596784661.27-18286-75430763482321/AnsiballZ_command.py'"

Видимо Вы переопределили параметр remote_tmp  в ansible.cfg
В предложенной мной конфигурации я предлагаю параметры:
```
remote_tmp = /tmp/${USER}/ansible
allow_world_readable_tmpfiles = false
```

**Comment by jidckii** [comment]
> Видимо Вы переопределили параметр remote_tmp в ansible.cfg

вот мой конфиг
```
[defaults]
action_plugins = ./plugins/actions
allow_world_readable_tmpfiles = false # or "true" if the temporary directory on the remote host is mounted with POSIX acls disabled or the remote machines use ZFS.
callback_whitelist = profile_tasks
display_skipped_hosts = false
hash_behaviour = merge
host_key_checking = false
interpreter_python = python3
remote_tmp = /tmp/${USER}/ansible
retry_files_enabled = False
roles_path = ./roles
timeout=60

[persistent_connection]
retries = 3
connect_timeout = 60
command_timeout = 30

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=30m
control_path = %(directory)s/ansible-%%r@%%h:%%p
pipelining = true
control_path_dir=/tmp
scp_if_ssh = true
```

> А в чём именно по Вашему мнению заключается магия?

Ну там в блоке что то невообразимое происходит, как по мне ... )

```
bootstrap:
  method: pgbackrest
  pgbackrest:
    command: /etc/patroni/pgbackrest_bootstrap.sh
    keep_existing_recovery_conf: True

```
Так же я не понимаю как это должно работать, если в роли с установкой pgbackrest, таска, которая рендерит `/etc/patroni/pgbackrest_bootstrap.sh` закомментирована. Я пытался понять почему так вышло по истории коммитов, но что то не допёр )

В общем то я не эксперт в патрони, буду благодарен, если поможете разобраться с инициализацией кластера с из бэкапа pgbackrest.
