### ISSUE TITLE
Improvement suggestion remove_cluster.yml

### ISSUE THREAD

**Issue by rrrru** [vitabaks/postgresql_cluster#449]
Update 
```
    - name: Stop Consul service
      ansible.builtin.service:
        name: consul
        state: stopped
        enabled: false
      when: remove_consul | bool
    - name: Delete Consul content
      ansible.builtin.file:
        path: "{{ consul_data_path }}"
        state: absent
      when: remove_consul | bool
```

To:

```
    - name: Remove KV items from Consul
      ansible.builtin.shell: |
        "consul kv delete -recurse service/{{ patroni_cluster_name }}"
      args:
        executable: /bin/bash
      ignore_errors: true
      when: remove_consul | bool
    - name: Stop Consul service
      ansible.builtin.service:
        name: consul
        state: stopped
        enabled: false
      when: remove_consul | bool
    - name: Delete Consul content
      ansible.builtin.file:
        path: "{{ consul_data_path }}"
        state: absent
      when: remove_consul | bool
```

Related https://github.com/vitabaks/postgresql_cluster/issues/448#issuecomment-1687024565
