### ISSUE TITLE
A slight tweak to your code

### ISSUE THREAD

**Issue by carlp101** [vitabaks/postgresql_cluster#48]
Hi,

Excellent work BTW.

FYI, I had to add the owner, group and mode lines to the following code in roles/patroni/tasks/main.yml to overcome restrictions  on a hardened Centos 7 image I was using. It would be appreciated if you could merge this tweak in to master.  
```
# Patroni configure
- name: Create conf directory
  file:
    path: /etc/patroni
    state: directory
    owner: postgres
    group: postgres
    mode: 0750
  tags: patroni, patroni_conf
```

Regards
Carl
