### ISSUE TITLE
etcd health check and service start

### ISSUE THREAD

**Issue by redy01** [vitabaks/postgresql_cluster#500]
OS RHEL9
etcd-3.5.10-1PGDG.rhel9.rpm

etcd/tasks/main.yml
```
128 - name: Wait until the etcd cluster is healthy
129      ansible.builtin.command: >
130        /usr/local/bin/etcdctl endpoint health
131        --endpoints=http://{{ inventory_hostname }}:2379
```
should not contain full path to etcdctl, it will break installation if package was used to install etcd and binary file was saved in different location. Removing full path will fix the issue

Service fail to start if members are not reachable f.ex. if firewall block etcd ports. can be fixed by adding task before health check:
```
- name: Open Firewall for etcd services
  ansible.posix.firewalld:
    port: 2378-2380/tcp
    immediate: true
    permanent: true
    state: enabled
  when: ansible_facts.services['firewalld.service'].state == 'running'
  tags: etcd, etcd_start
```

One more task can be helpful, located in pre_tasks section:
deploy_pgcluster.yml
```
 - name: Fetch services facts
    ansible.builtin.service_facts:
    tags: always
```
