### ISSUE TITLE
вариант реализации callback.sh

### ISSUE THREAD

**Issue by sgrinko** [vitabaks/postgresql_cluster#53]
Добрый день!

Спасибо большое за вашу работу!

Предложение:
предлагаю добавить в master ветку простую default реализацию информирования об изменении ролей кластера
приложил свой файл callback.sh.j2
для отсылки письма я использую программу mutt, а для настройки написал простую роль `email` которую также вызываю при настройке кластера в deploy_pgcluster.yml
```
    - role: email
      when: email_install|bool
```

Вид формируемого письма:
![изображение](https://user-images.githubusercontent.com/10084993/90278560-3f6c7f80-de70-11ea-9d9f-64fb221ae905.png)

[callback.sh.zip](https://github.com/vitabaks/postgresql_cluster/files/5076212/callback.sh.zip)

Добавил переменную в которой указываю кому присылать письмо
`patroni_callback_email`

В каталог `roles\patroni\templates`
добавил приложенный `callback.sh.j2` файл и поправил файл `patroni.yml.j2`
```
  callbacks:
    on_start: /etc/patroni/callback.sh
    on_stop: /etc/patroni/callback.sh
    on_restart: /etc/patroni/callback.sh
    on_reload: /etc/patroni/callback.sh
    on_role_change: /etc/patroni/callback.sh
```

В файл `roles\patroni\tasks\main.yml`
```
- name: Generate callback file "/etc/patroni/callback.sh"
  template:
    src: templates/callback.sh.j2
    dest: /etc/patroni/callback.sh
    owner: postgres
    group: postgres
    mode: 0755
  when: existing_pgcluster is not defined or not existing_pgcluster|bool
  tags: patroni, patroni_conf
```
и в - block:  # for add_pgnode.yml
```
    - name: Fetch callback.sh file from master
      run_once: true
      fetch:
        src: /etc/patroni/callback.sh
        dest: files/callback.sh
        validate_checksum: true
        flat: true
      delegate_to: "{{ groups.master[0] }}"

    - name: Copy callback.sh conf file to replica

      copy:
        src: files/callback.sh
        dest: /etc/patroni/callback.sh
        owner: postgres
        group: postgres
        mode: 0640
```

детали моей роли email:
vars/main.yml
```
# to set up mail
email_install: true                             # true if you need to configure mail
#email_realname: "db-postgres"                  # name for email send for "from". Comment for value as ansible_hostname 
email_machine_name: "email.dvl.ru"              # name email server
email_domen_name: "dvl.ru"                      # part of name is "Hostname"
email_for_test: "my_email@work.ru"              # address for checking the health of mail settings
```
файл с ролью приложил, вдруг кому-то это будет полезно, а вдруг это понравится и войдет в настройку кластера :)

[email.yml.zip](https://github.com/vitabaks/postgresql_cluster/files/5076221/email.yml.zip)

Ещё раз большое спасибо за вашу работу!
