### ISSUE TITLE
добавить поддержку pg_ident.conf

### ISSUE THREAD

**Issue by sgrinko** [vitabaks/postgresql_cluster#55]
В моих серверах используется настроечный файл `pg_ident.conf`
Однако в вашей редакции этот файл обойдён вниманием :)
Предлагаю добавить его поддержку при настройке кластера, так как это один из важных файлов с настройками.
Я добавил такую поддержку по аналогии с файлом `pg_hba.conf`
добавил в файл `vars/main.yml`
```
# specify additional hosts that will be added to the pg_ident.conf
postgresql_pg_ident:
  - {mapname: "main", system_username: "postgres", pg_username: "backup"} # default values is set for pg_probackup utility
```
в каталог `roles/patroni/templates` добавил новый шаблон `pg_ident.conf.j2` внутри которого вот такой текст:
```
# MAPNAME       SYSTEM-USERNAME         PG-USERNAME
{% for client in postgresql_pg_ident %}
  {{ client.mapname.ljust(25) |default('main') }}{{ client.system_username.ljust(25) |default('postgres') }}{{ client.pg_username.ljust(25) |default('backup') }}
{% endfor %}
```
в `roles/patroni/tasks/main.yml` добавил следующие блоки:
```
- block:  # when postgresql exists (master)
...
    - name: Prepare PostgreSQL | generate pg_ident.conf on Master
      template:
        src: templates/pg_ident.conf.j2
        dest: "{{ postgresql_conf_dir }}/pg_ident.conf"
        owner: postgres
        group: postgres
        mode: 0640
...
- block:  # pg_hba (using a templates/pg_hba.conf.j2)
...
    - name: Prepare PostgreSQL | generate pg_ident.conf
      template:
        src: templates/pg_ident.conf.j2
        dest: "{{ postgresql_conf_dir }}/pg_ident.conf"
        owner: postgres
        group: postgres
        mode: 0640
...
- block:  # for add_pgnode.yml
...
    - name: Prepare PostgreSQL | fetch pg_ident.conf file from master
      run_once: true
      fetch:
        src: "{{ postgresql_conf_dir }}/pg_ident.conf"
        dest: files/pg_ident.conf
        validate_checksum: true
        flat: true
      delegate_to: "{{ groups.master[0] }}"

    - name: Prepare PostgreSQL | copy pg_ident.conf file to replica
      copy:
        src: files/pg_ident.conf
        dest: "{{ postgresql_conf_dir }}/pg_ident.conf"
        owner: postgres
        group: postgres
        mode: 0640
...
```

Благодарю вас за вашу работу!
