### ISSUE TITLE
Consul service structure clarification needed

### ISSUE THREAD

**Issue by garry-t** [vitabaks/postgresql_cluster#640]
What is the logic here? 
https://github.com/vitabaks/postgresql_cluster/blob/e66f2bb19c166990a57afd566f46de941a581340/vars/main.yml#L115-L129

If you run it as is you will get replica only service for all pg nodes. Because name parameter same and overwrites previous file.

What expected result here ? You need to register all services in all nodes, but healthy will be only those where roles are match. 

Thanks

**Comment by vitabaks** [comment]
Have you already tried deploying a cluster with consul?

**Comment by garry-t** [comment]
I'm debugging role, I have my own consul cluster so role is not completely fits to my needs. Consul role mapped to my own, but it doesnt matter. 
I run my consul role with your default params and in my case all pg nodes after consul installation has replica files and no master.  
this is confused me. When I set like this: 
```
consul_services:
  - name: "{{ patroni_cluster_name }}-master"
    tags: ['master', 'primary']
    port: "{{ pgbouncer_listen_port }}"  # or "{{ postgresql_port }}" if pgbouncer_install: false
    checks:
      - { id: "{{ patroni_cluster_name }}-master", http: "http://{{ inventory_hostname }}:{{ patroni_restapi_port }}/primary", interval: "2s", name: "Patroni Checks"}
      - { id: "{{ patroni_cluster_name }}-bouncer-master", name: "PGBouncer Check", args: ["systemctl", "status", "pgbouncer"], interval: "5s" }  # comment out this check if pgbouncer_install: false
  - name: "{{ patroni_cluster_name }}-replica"
    tags: ['replica']
    port: "{{ pgbouncer_listen_port }}"
    checks:
      - { id: "{{ patroni_cluster_name }}-replica", name: "Patroni Checks", http: "http://{{ inventory_hostname }}:{{ patroni_restapi_port }}/replica?lag={{ patroni_maximum_lag_on_replica }}", interval: "2s" }
      - { id: "{{ patroni_cluster_name }}-bouncer-replica", name: "PGBouncer Check", args: ["systemctl", "status", "pgbouncer"], interval: "5s" }
```

I see at least in consul all registered services but in unhealthy state which is now for me ok. So question is still relevant for me shall leave your approach? Or it is a bug and we need to change it. I didn't use patroni previously so I don't know what is correct structure should be. 
Yeah, I changed structure of parameters to avoid [bug](https://github.com/hashicorp/consul/issues/6923#issuecomment-564476529).
