### ISSUE TITLE
How to configure WAL-G?

### ISSUE THREAD

**Issue by algoritmsystems** [vitabaks/postgresql_cluster#692]
How to configure WAL-G? for restore and backup? I've a minio server on 172.20.20.22. 
> cat /etc/default/minio
MINIO_ROOT_USER=myminioadmin
MINIO_ROOT_PASSWORD=myminioadmin
MINIO_VOLUMES="/home/ubuntu/data"
MINIO_OPTS="--console-address :9001"

vars/main.yml
```yaml
patroni_cluster_bootstrap_method: "wal-g" 
#...
patroni_create_replica_methods:
- wal_g
- basebackup
#...
postgresql_restore_command: "{{ wal_g_path }} wal-fetch %f %p"
#...
wal_g_install: true 
wal_g_version: "3.0.0"
wal_g_path: "/usr/local/bin/wal-g"
wal_g_json: 
  - { option: "PGDATA", value: "{{ postgresql_data_dir }}" }
  - { option: "PGHOST", value: "{{ postgresql_unix_socket_dir }}" }
  - { option: "PGPORT", value: "{{ postgresql_port }}" 
  - { option: "PGUSER", value: "{{ patroni_superuser_username }}" }
  - { option: "AWS_S3_FORCE_PATH_STYLE", value: "true" }  
  - { option: "AWS_ENDPOINT", value: "http://172.20.20.22:9000" }
wal_g_archive_command: "{{ wal_g_path }} wal-push %p"
wal_g_patroni_cluster_bootstrap_command: "{{ wal_g_path }} backup-fetch {{ postgresql_data_dir }} LATEST"
```
ERROR:
```
FAILED! => {"changed": false, "cmd": "/usr/bin/gmake deps USE_BROTLI=1 USE_LIBSODIUM=1", "msg": "CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):\n  Compatibility with CMake < 2.8.12 will be removed from a future version of\n  CMake.\n\n  Update the VERSION argument <min> value or use a ...<max> suffix to tell\n  CMake that the project does not need compatibility with older versions.\n\n\n-- Compiler is not EMSCRIPTEN\n\ngzip: stdin: not in gzip format\ntar: Child returned status 1\ntar: Error is not recoverable: exiting now\ngmake: *** [Makefile:296: link_libsodium]
```
