### ISSUE TITLE
Failed to find any configured storage

### ISSUE THREAD

**Issue by algoritmsystems** [vitabaks/postgresql_cluster#696]
I depoloyed postgresql cluster and during installion the database with initdb was deployed to my minio server, but after it can't  find any configured storage:
>wal-g backup-push /var/lib/postgresql/14/main/
ERROR: 2024/07/13 18:09:47.369761 Failed to find any configured storage

main.yml config is:
```yaml
wal_g_install: true  
wal_g_version: "3.0.2"
wal_g_path: "/usr/local/bin/wal-g"
wal_g_json:  # config https://github.com/wal-g/wal-g#configuration
  - { option: "AWS_ACCESS_KEY_ID", value: "myminioadmin" }
  - { option: "AWS_SECRET_ACCESS_KEY", value: "myminiopass" } 
  - { option: "WALG_S3_PREFIX", value: "s3://mnt/" } 
  - { option: "WALG_COMPRESSION_METHOD", value: "brotli" }   
  - { option: "AWS_ENDPOINT", value: "http://172.20.20.26:9000" }  
  - { option: "AWS_S3_FORCE_PATH_STYLE", value: "true" } 
  - { option: "PGDATA", value: "{{ postgresql_data_dir }}" }
  - { option: "PGHOST", value: "{{ postgresql_unix_socket_dir }}" }
  - { option: "PGPORT", value: "{{ postgresql_port }}" }
  - { option: "PGUSER", value: "{{ patroni_superuser_username }}" }
```
