### ISSUE TITLE
Backup and restore question(pgbackrest)

### ISSUE THREAD

**Issue by BabaTataKaka** [vitabaks/postgresql_cluster#701]
I'm trying to run a PITR on an existing postgres cluster:

ansible-playbook -i ./inventory/dev.yml  deploy_pgcluster.yml --tags point_in_time_recovery

The restore is successful on the master but it fail on the replica server due to the backup not being created on the replicas. I've asked a question on the backrest  github(https://github.com/pgbackrest/pgbackrest/issues/2400) about that problem and they told me that you cannot run a backup on a standby server(which I think is required by patroni: hot_standby=on). The solution would be to define  pg1(master) and pg2(standby) in the pgbackrest config.
The postgres_cluster playbook out of the box settings do not suggest such config and wouldn't make sense with patroni(HA).  When doing the PITR the playblook clearly try to restore both the master and replicas but the suggested pgbackrest config for the backup doesn't allow it. Is there something I'm doing wrong?

**Comment by vitabaks** [comment]
Hi @BabaTataKaka 

The provided configuration in `vars/main.yml` is just an example.

For PITR of the entire cluster, it is necessary that the backups are not local but stored on a dedicated pgBackRest server, S3, or similar storage.

**Comment by vitabaks** [comment]
example of a configuration with a dedicated pgBackRest server:

```yaml
# pgBackRest
pgbackrest_install: true
pgbackrest_install_from_pgdg_repo: true
pgbackrest_stanza: "{{ patroni_cluster_name }}"
pgbackrest_repo_type: "posix"
pgbackrest_repo_host: "***.**.***.**"  # dedicated repository host
pgbackrest_repo_user: "postgres"
pgbackrest_conf_file: "/etc/pgbackrest/pgbackrest.conf"

pgbackrest_conf:
  global:
    - { option: "log-level-file", value: "detail" }
    - { option: "log-path", value: "/var/log/pgbackrest" }
    - { option: "repo1-host", value: "{{ pgbackrest_repo_host }}" }
    - { option: "repo1-host-user", value: "{{ pgbackrest_repo_user }}" }
    - { option: "repo1-type", value: "{{ pgbackrest_repo_type | lower }}" }
    - { option: "repo1-path", value: "/var/lib/pgbackrest" }
    - { option: "spool-path", value: "/var/spool/pgbackrest" }
    - { option: "archive-async", value: "y" }
    - { option: "archive-get-queue-max", value: "1GiB" }
  stanza:
    - { option: "process-max", value: "4" }
    - { option: "log-level-console", value: "info" }
    - { option: "recovery-option", value: "recovery_target_action=promote" }
    - { option: "pg1-socket-path", value: "{{ postgresql_unix_socket_dir }}" }
    - { option: "pg1-path", value: "{{ postgresql_data_dir }}" }

pgbackrest_server_conf:
  global:
    - { option: "process-max", value: "4" }
    - { option: "log-level-file", value: "detail" }
    - { option: "log-level-console", value: "info" }
    - { option: "log-path", value: "/var/log/pgbackrest" }
    - { option: "repo1-type", value: "{{ pgbackrest_repo_type | lower }}" }
    - { option: "repo1-path", value: "/var/lib/pgbackrest" }
    - { option: "repo1-retention-full", value: "30" }
    - { option: "repo1-retention-full-type", value: "time" }
    - { option: "repo1-retention-history", value: "365" }
    - { option: "repo1-bundle", value: "y" }
    - { option: "repo1-block", value: "y" }
    - { option: "start-fast", value: "y" }
    - { option: "stop-auto", value: "y" }
    - { option: "resume", value: "n" }
    - { option: "link-all", value: "y" }
    - { option: "archive-check", value: "y" }
    - { option: "archive-copy", value: "n" }
    - { option: "backup-standby", value: "y" }
# the stanza section will be generated automatically
```
