### ISSUE TITLE
Issue on task Extract "etcd" into /tmp when user is root

### ISSUE THREAD

**Issue by aliencrash** [vitabaks/postgresql_cluster#73]
Running your ansible I'm having this issue with task Extract "etcd" into /tmp in Centos 8.

"err": "/usr/bin/gtar: etcd-v3.3.23-linux-amd64/etcdctl: Cannot change ownership to uid 630384594, gid 600260513: Invalid argument\n/usr/bin/gtar: etcd-v3.3.23-linux-amd64/README.md: Cannot change ownership to uid 630384594, gid 600260513: Invalid argument\n/usr/bin/gtar: etcd-v3.3.23-linux-amd64/etcd: Cannot change ownership to uid 630384594, gid 600260513: Invalid argument\n/usr/bin/gtar: etcd-v3.3.23-linux-amd64/Documentation/production-users.md: Cannot change ownership to uid 630384594, gid 600260513: Invalid argument\n/usr/bin/gtar: etcd-v3.3.23-linux-amd64/Documentation/demo.md: Cannot change ownership to uid 630384594, gid 600260513: Invalid argument\n/usr/bin/gtar: etcd-v3.3.23-linux-amd64/Documentation/op-guide/etcd-sample-grafana.png:

**Comment by vitabaks** [comment]
There hasn't been such a problem yet.

Try adding owner and group to unarchive module
roles/etcd/tasks/main.yml

```
    - name: Extract "etcd" into /tmp
      unarchive:
        src: "/tmp/{{ etcd_package_repo | basename }}"
        dest: /tmp/
        owner: root
        group: root
        remote_src: true
```
