### ISSUE TITLE
Console (UI): Expert mode

### ISSUE THREAD

**Issue by vitabaks** [vitabaks/postgresql_cluster#756]
With the release version [2.0](https://github.com/vitabaks/postgresql_cluster/releases/tag/2.0.0), we introduced a Console (UI) that provides an easy way to deploy clusters using a graphical interface. Now we are planning to add **Expert Mode** to unlock advanced user interface options tailored for experienced users.

Expert mode is disabled by default to provide a simple mode to simplify the user experience and can be enabled (if necessary) on the Settings page.

![Image](https://github.com/user-attachments/assets/9779b6d5-8b10-4450-800d-ca9e7d0a0c1f)

This mode reveals additional settings and features that allow for precise configuration of clusters, including complex parameter adjustments not visible in the standard mode, including:

### 1. Custom server type

The ability to specify another server (instance) type that is not represented in the console list (for cloud deployments).
### 2. Spot instances

The ability to select Spot instances when creating a cluster (for cloud deployments).

![image](https://github.com/user-attachments/assets/cbe4878d-faf9-4103-927f-a77f9746588c)

### 3. Volume and File System Type

The ability to select volume and file system type when creating a cluster (for cloud deployments).

![image](https://github.com/user-attachments/assets/231163e8-e315-4a54-9c4f-94974c35d4bd)

### 4. Network

The ability to specify a Network/VPC (for cloud deployments).
  - If provided, the server will be added to this network (needs to be created beforehand).

### 5. DCS

The ability to select the type of DCS (etcd or consul), deploy new servers, or use an already deployed DCS cluster.

![image](https://github.com/user-attachments/assets/d7ae7eb0-b412-4bc0-a6e1-d7b7105849cd)

### 6. Data directory

The ability to redefine the data directory path.

![image](https://github.com/user-attachments/assets/d720dde0-a3ec-4649-a6c5-d98f58dd0304)

### 7. Databases

The ability to add databases and users when creating a cluster.

![image](https://github.com/user-attachments/assets/c194b6ef-205f-40b9-b81a-ec7cfb9333b8)

### 8. Connection pools

The ability to configure PgBouncer connection pooler when creating a cluster.

![image](https://github.com/user-attachments/assets/fdae479f-704a-4585-9b42-3311232484c1)

### 9. Extensions

The ability to choosing extensions when creating a cluster.

![image](https://github.com/user-attachments/assets/62b0703b-ce2e-4a01-8a29-df216551912c)

### 10. Backups

The ability to configure Backups when creating a cluster.

![image](https://github.com/user-attachments/assets/23de5037-b37c-4031-8370-95e13b11dde2)

### 11. Postgres and system settings

The ability to configure Postgres and system (kernel) settings when creating a cluster.

![image](https://github.com/user-attachments/assets/9c02d9cc-f017-4d25-b745-2b6cfb9d580b)

### 12. Additional settings

The ability to choosing additional settings when creating a cluster.

![image](https://github.com/user-attachments/assets/8149b294-f52b-456b-afe2-31e775345f7b)

### 13. YAML tab

Another function for "Expert Mode" could be to provide a "YAML tab" where all current parameters are displayed in the form of variables. This tab would also allow users to set predefined values for functions that may not have been added to the UI yet but are available through automation capabilities.

> [!NOTE]
> Access to the Figma project with all implementation details will be provided during development.

---
Consider sponsoring the project via [GitHub](https://github.com/sponsors/vitabaks) or [Patreon](https://patreon.com/vitabaks)

**Comment by vitabaks** [comment]
If you're interested in this feature, please consider becoming a [sponsor](https://github.com/vitabaks/postgresql_cluster?tab=readme-ov-file#sponsor-this-project).

The development of this feature requires sponsorship to fund developer efforts. If you're already a sponsor and are interested in this feature, please leave a comment here so we can prioritize this issue accordingly.

We also welcome contributions from those willing to dedicate their time to implement this feature on a voluntary basis. Please see the [Contributing Guide](https://github.com/vitabaks/postgresql_cluster/blob/master/CONTRIBUTING.md) for more information.

**Comment by vitabaks** [comment]
Also consider the possibility of managing public access, setting variables:
```yaml
ssh_public_access: true  # Allow public ssh access (required for deployment from the public network).
ssh_public_allowed_ips: ""  # (comma-separated list of IP addresses in CIDR format) If empty, then public access is allowed for any IP address.
netdata_public_access: true  # Allow access to the Netdata monitoring from the public network (if 'netdata_install' is 'true').
netdata_public_allowed_ips: ""  # (comma-separated list of IP addresses in CIDR format) If empty, then public access is allowed for any IP address.
database_public_access: false  # Allow access to the database from the public network.
database_public_allowed_ips: ""  # (comma-separated list of IP addresses in CIDR format) If empty, then public access is allowed for any IP address.
```
