### ISSUE TITLE
haproxy failed to start after the host restarts，log is "Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]"

### ISSUE THREAD

**Issue by marsdonne** [vitabaks/postgresql_cluster#8]
haproxy failed to start after the host restarts,   i searched the log by:

`journalctl -b -0 -u haproxy`

got a message:

`
Sep 19 21:25:11 pgnode01 haproxy[2437]: [ALERT] 261/212511 (2437) : Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]
`

run: `ll /run/haproxy` is: cannot access /run/haproxy: No such file or directory
run: ‘mkdir /run/haproxy’ and `systemctl start haproxy` it has started

but，Why is it running very well when it was just deployed?

**Comment by vitabaks** [comment]
interestingly, I did not observe such an effect.  
What is your linux distribution?

**Comment by marsdonne** [comment]
CentOS Linux release 7.6.1810 (Core)

reason： the directory '/run/haproxy' is lost after host restart

**Comment by vitabaks** [comment]
> Why is it running very well when it was just deployed?

This directories are created during deployment.

```
- name: haproxy | create directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: haproxy
    group: haproxy
  loop:
    - /etc/haproxy
    - /var/run/haproxy
    - /var/lib/haproxy/dev
```

> Haproxy needs to write to /run/haproxy/admin.sock but it wont create the directory for you

I'll fix it now.
